version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - skywalking-net

  oap:
    image: apache/skywalking-oap-server:9.0.0
    container_name: oap
    depends_on:
      - elasticsearch
    environment:
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    ports:
      - 11800:11800
      - 12800:12800
    networks:
      - skywalking-net

  ui:
    image: apache/skywalking-ui:9.0.0
    container_name: ui
    depends_on:
      - oap
    environment:
      - SW_OAP_ADDRESS=oap:12800
    ports:
      - 8190:8080
    networks:
      - skywalking-net

networks:
  skywalking-net:
    driver: bridge